name: Rust Tests

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  rust-test:
    name: Rust tests - 1.99.0
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        run: rustup toolchain install 1.99.0 --profile minimal --component rustfmt

      - name: Check formatting
        run: cargo +1.99.0 fmt --all -- --check

      - name: Test on Linux
        run: cargo +1.99.0 test --locked --verbose --target x86_64-unknown-linux-gnu

      - name: Check echo server example
        run: cargo +1.99.0 check --locked --example bridge_echo_server --target x86_64-unknown-linux-gnu